# -*- coding: utf-8 -*-
"""Водовоздушный_эжектор_ipynb_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZ_dYiiWHyv6HixoJNmEl_17ABTeb9EG
"""

import math
import matplotlib.pyplot as plt

class WaterAirEjector:
    def __init__(self,G_air, P_water, P_air, T_water, T_air, Pc, uo,choice):
        self.G_air = G_air
        self.P_water = P_water
        self.P_air = P_air
        self.T_water = T_water
        self.T_air = T_air
        print(f"pc12:{Pc}")
        print(f"uo12:{uo}")
        print(f"choice):{choice}")
        if choice.lower() == "pc":
            self.Pc = Pc
            self.uo = None
        elif choice.lower() == "uo":
            self.uo = uo
            self.Pc = None
        else:
            raise ValueError("Неверный выбор. Введите 'uo' или 'Pc'.")
        print(f"pc:{self.Pc}")
        print(f"uo:{self.uo}")

    def calculate_Pc(self, uo, delta_P_water, P_air):
        Pc = (delta_P_water / ((uo + 1) / 0.85)**2) + P_air
        return Pc

    def calculate_parameters(self):
        # Константы
        R_air = 292.7  # Газовая постоянная для воздуха, Дж/(кг·К)
        rho_water = 1000  # Плотность воды при 20 градусах, кг/м³
        fi1 = 0.95
        fi2 = 0.975  # Коэффициент скорости камеры смешения
        fi3 = 0.9
        fi4 = 0.925

        # Преобразование температур в Кельвины
        T_air_K = self.T_air + 273.15
        T_water_K = self.T_water + 273.15
        P_vapor = 1.7  # Парциальное давление водяного пара, кПа

        # Определяем перепад давлений
        delta_P_water = self.P_water - self.P_air  # Перепад давлений рабочей воды
        
        
        self.delta_Pc = self.Pc - self.P_air # Перепад давлений, создаваемый эжектором

        if self.Pc is not None:
            # Определяем объемный коэффициент инжекции
            self.uo = 0.85 * (math.sqrt(delta_P_water / self.delta_Pc)) - 1
        elif self.uo is not None:
            # Рассчитываем давление на выходе
            self.Pc = self.calculate_Pc(self.uo, delta_P_water, self.P_air)
            

        # Основной геометрический параметр эжектора
        n = delta_P_water / self.delta_Pc

        # Объемный расход паровоздушной смеси, м³/ч
        Q_air = ((self.G_air * R_air) * T_water_K) / ((self.P_air - P_vapor) * 10**3)

        # Объемный расход рабочей воды, м³/ч
        Q_water = Q_air / self.uo

        # Минимальное давление рабочей воды, при котором возможна работа эжектора
        P_water_min = (self.Pc / 2) * (delta_P_water / self.delta_Pc)

        # Максимальный объемный коэффициент инжекции
        uo_max = (0.35 * (self.P_water - self.Pc)) / ((self.Pc / 2.7) - P_vapor)

        # Оптимальное отношение сечений камеры смешения и рабочего сопла
        n_opt = 1.25 * uo_max + 1

        # Расчет выходного сечения рабочего сопла и входного сечения камеры смешения, м²
        delta_P_MPa = delta_P_water / 1000
        fp1 = (Q_water * 10**6) / (fi1 * 3600 * (math.sqrt(2 * delta_P_MPa * 10**6 * 10**-3)))
        f3 = (Q_water * 10**6 / (fi1 * 3600 * math.sqrt(2 * delta_P_MPa * 10**6 * 10**-3))) * ((self.P_water - self.P_air) / (self.Pc - self.P_air))



        # Расчет диаметров
        d1 = 2 * math.sqrt(fp1 / math.pi)
        d3 = 2 * math.sqrt(f3 / math.pi)

        # Длина свободной струи (расстояние выходного сечения рабочего сопла от входного сечения цилиндрической камеры смешения)
        l_c = 1.25 * d3

        # Длина камеры смешения
        l_k = 9 * d3

        # Оптимальная длина камеры смешения
        l_k_opt = 15 * ((f3/fp1) - 1) * d1

        return {
            "Перепад давлений рабочей воды, кПа": delta_P_water,
            "Перепад давлений, создаваемый эжектором, кПа": self.delta_Pc,
            "Парциальное давление водяного пара, кПа": f"{P_vapor:.1f}",
            "Объемный коэффициент инжекции": f"{self.uo:.2f}",
            "Давление на выходе, Pc (кПа)": f"{self.Pc:.2f}",
            "Основной геометрический параметр эжектора": f"{n:.1f}",
            "Минимальное давление рабочей воды, при котором возможна работа эжектора, кПа": f"{P_water_min:.2f}",
            "Максимальный объемный коэффициент инжекции": f"{uo_max:.2f}",
            "Оптимальное отношение сечений камеры смешения и рабочего сопла":f"{n_opt:.1f}",
            "Объемный расход по воздуху, м³/ч": f"{Q_air:.2f}",
            "Объемный расход по воде, м³/ч": f"{Q_water:.2f}",
            "Выходное сечение рабочего сопла fp1, мм²": f"{fp1:.2f}",
            "Входное сечение камеры смешения f3, мм²": f"{f3:.2f}",
            "Диаметр сопла, мм": f"{d1:.2f}",
            "Диаметр камеры смешения, мм": f"{d3:.2f}",
            "Длина свободной струи, мм": f"{l_c:.2f}",
            "Длина камеры смешения, мм": f"{l_k:.2f}",
            "Оптимальная длина камеры смешения, мм": f"{l_k_opt:.2f}"
        }